// Test generated by RoostGPT for test SocialMediaTest using AI Type Open AI and AI Model gpt-4

const request = require('supertest');
const express = require('express');
const app = express();
const path = require('path');

app.get("*", (req, res) => {
  res.sendFile(path.resolve(__dirname, "../frontend/build/index.html"));
});

describe('Test the root path', () => {
  test('It should response the GET method', async () => {
    const response = await request(app).get('/');
    expect(response.statusCode).toBe(200);
  });

  test('It should return the index.html file', async () => {
    const response = await request(app).get('/');
    const expectedPath = path.resolve(__dirname, "../frontend/build/index.html");
    expect(response.text).toContain(expectedPath);
  });
});
