// Test generated by RoostGPT for test TestA using AI Type Open AI and AI Model gpt-4

const request = require('supertest');
const express = require("express");
const app = express();
const cookieParser = require("cookie-parser");
const path = require("path");
if (process.env.NODE_ENV !== "production") {
  require("dotenv").config({ path: "backend/config/config.env" });
}

// Using Middlewares
app.use(express.json({ limit: "50mb" }));
app.use(express.urlencoded({ limit: "50mb", extended: true }));
app.use(cookieParser());

// Importing Routes
const post = require("./routes/post");
const user = require("./routes/user");

app.get("*", (req, res) => {
  res.sendFile(path.resolve(__dirname, "../frontend/build/index.html"));
});

describe('Test the root path', () => {
    test('It should respond with a 200 status code', async () => {
        const response = await request(app).get('/');
        expect(response.statusCode).toBe(200);
    });
    test('It should respond with a 404 status code for non-existing routes', async () => {
        const response = await request(app).get('/nonExistentRoute');
        expect(response.statusCode).toBe(404);
    });
});
