// Test generated by RoostGPT for test TestA using AI Type Open AI and AI Model gpt-4

const request = require('supertest');
const app = require('./app');
const { connectDatabase } = require("./config/database");
const cloudinary = require("cloudinary")

describe('Test the root path', () => {
  test('It should response the GET method', async () => {
    const response = await request(app).get('/');
    expect(response.statusCode).toBe(200);
  });
});

describe('Test the server listen method', () => {
  let server;

  beforeAll(async () => {
    server = app.listen(3000, () => {
      console.log('Server is running on port 3000');
    });
  });

  afterAll(async () => {
    server.close();
  });

  test('It should start and stop the server', async () => {
    const response = await request(server).get('/');
    expect(response.statusCode).toBe(200);
  });
});
