// Test generated by RoostGPT for test SocialMediaTest using AI Type Open AI and AI Model gpt-4

const request = require('supertest');
const app = require('./app');
const { connectDatabase } = require("./config/database");
const cloudinary = require("cloudinary")

describe('Test the root path', () => {
    test('It should response the GET method', async () => {
        const response = await request(app).get('/');
        expect(response.statusCode).toBe(200);
    });

    test('It should log the server running message', () => {
        console.log = jest.fn();
        app.listen(process.env.PORT, () => {
            console.log(`Server is running on port ${process.env.PORT}`);
        });
        expect(console.log).toHaveBeenCalledWith(`Server is running on port ${process.env.PORT}`);
    });
});
