// Test generated by RoostGPT for test SocialMediaTest using AI Type Open AI and AI Model gpt-4

const axios = require('axios');
const { updatePassword } = require('./User');

jest.mock('axios');

describe('updatePassword', () => {
  beforeEach(() => {
    axios.put.mockClear();
  });

  test('dispatches updatePasswordRequest and updatePasswordSuccess on successful password update', async () => {
    const dispatch = jest.fn();
    const oldPassword = 'oldPassword';
    const newPassword = 'newPassword';
    const response = { data: { message: 'Password updated successfully' } };

    axios.put.mockResolvedValueOnce(response);

    await updatePassword(oldPassword, newPassword)(dispatch);

    expect(dispatch).toHaveBeenCalledWith({ type: 'updatePasswordRequest' });
    expect(axios.put).toHaveBeenCalledWith('/api/v1/update/password', { oldPassword, newPassword }, { headers: { "Content-Type": "application/json" } });
    expect(dispatch).toHaveBeenCalledWith({ type: 'updatePasswordSuccess', payload: response.data.message });
  });

  test('dispatches updatePasswordRequest and updatePasswordFailure on failed password update', async () => {
    const dispatch = jest.fn();
    const oldPassword = 'oldPassword';
    const newPassword = 'newPassword';
    const error = { response: { data: { message: 'Failed to update password' } } };

    axios.put.mockRejectedValueOnce(error);

    await updatePassword(oldPassword, newPassword)(dispatch);

    expect(dispatch).toHaveBeenCalledWith({ type: 'updatePasswordRequest' });
    expect(axios.put).toHaveBeenCalledWith('/api/v1/update/password', { oldPassword, newPassword }, { headers: { "Content-Type": "application/json" } });
    expect(dispatch).toHaveBeenCalledWith({ type: 'updatePasswordFailure', payload: error.response.data.message });
  });
});
