// Test generated by RoostGPT for test TestA using AI Type Open AI and AI Model gpt-4

const axios = require("axios");
const { deletePost } = require("./Post");

jest.mock('axios');

describe("deletePost", () => {
  let id;
  let dispatch;

  beforeEach(() => {
    id = "12345";
    dispatch = jest.fn();
  });

  it("should dispatch deletePostRequest action", async () => {
    axios.delete.mockResolvedValue({});
    await deletePost(id)(dispatch);
    expect(dispatch).toHaveBeenCalledWith({ type: "deletePostRequest" });
  });

  it("should dispatch deletePostSuccess action when axios request is successful", async () => {
    const message = "Post deleted successfully";
    axios.delete.mockResolvedValue({ data: { message } });
    await deletePost(id)(dispatch);
    expect(dispatch).toHaveBeenCalledWith({ type: "deletePostSuccess", payload: message });
  });

  it("should dispatch deletePostFailure action when axios request fails", async () => {
    const message = "Error deleting post";
    axios.delete.mockRejectedValue({ response: { data: { message } } });
    await deletePost(id)(dispatch);
    expect(dispatch).toHaveBeenCalledWith({ type: "deletePostFailure", payload: message });
  });
});
