// Test generated by RoostGPT for test SocialMediaTest using AI Type Open AI and AI Model gpt-4

const axios = require('axios');
const { loadUser } = require('./User');

jest.mock('axios');

describe('loadUser', () => {
  beforeEach(() => {
    axios.get.mockClear();
  });

  test('should dispatch LoadUserRequest action', async () => {
    const dispatch = jest.fn();
    await loadUser()(dispatch);

    expect(dispatch).toHaveBeenCalledWith({
      type: 'LoadUserRequest'
    });
  });

  test('should dispatch LoadUserSuccess action on successful API call', async () => {
    const user = { id: '1', name: 'John Doe' };
    axios.get.mockResolvedValueOnce({ data: { user } });

    const dispatch = jest.fn();
    await loadUser()(dispatch);

    expect(dispatch).toHaveBeenCalledWith({
      type: 'LoadUserSuccess',
      payload: user
    });
  });

  test('should dispatch LoadUserFailure action on failed API call', async () => {
    const message = 'Error loading user';
    axios.get.mockRejectedValueOnce({ response: { data: { message } } });

    const dispatch = jest.fn();
    await loadUser()(dispatch);

    expect(dispatch).toHaveBeenCalledWith({
      type: 'LoadUserFailure',
      payload: message
    });
  });
});
