// Test generated by RoostGPT for test ExpressJs using AI Type Open AI and AI Model gpt-4

const axios = require("axios");
const { getAllUsers } = require("./User");
const { store } = require('./store');

jest.mock('axios');

describe("getAllUsers", () => {
  beforeEach(() => {
    store.clearActions();
  });

  it("dispatches allUsersRequest and allUsersSuccess actions on success", async () => {
    const users = [{ id: 1, name: 'John Doe' }];
    const resp = { data: { users } };
    axios.get.mockResolvedValue(resp);

    await store.dispatch(getAllUsers());
    const actions = store.getActions();

    expect(actions[0]).toEqual({ type: 'allUsersRequest' });
    expect(actions[1]).toEqual({ type: 'allUsersSuccess', payload: users });
  });

  it("dispatches allUsersRequest and allUsersFailure actions on failure", async () => {
    const errorMessage = 'Error while fetching users';
    axios.get.mockRejectedValue({ response: { data: { message: errorMessage } } });

    await store.dispatch(getAllUsers());
    const actions = store.getActions();

    expect(actions[0]).toEqual({ type: 'allUsersRequest' });
    expect(actions[1]).toEqual({ type: 'allUsersFailure', payload: errorMessage });
  });
});
