// Test generated by RoostGPT for test SocialMediaTest using AI Type Open AI and AI Model gpt-4

const axios = require("axios");
const { deleteMyProfile } = require("./User");
const { createStore } = require("redux");

jest.mock("axios");

describe("deleteMyProfile", () => {
  let store;
  let dispatch;

  beforeEach(() => {
    dispatch = jest.fn();
    store = createStore(() => ({}));
    store.dispatch = dispatch;
  });

  test("should dispatch deleteProfileRequest action", async () => {
    axios.delete.mockResolvedValueOnce({ data: { message: "Profile deleted successfully" } });

    await deleteMyProfile()(store.dispatch);

    expect(dispatch).toHaveBeenCalledWith({ type: "deleteProfileRequest" });
  });

  test("should dispatch deleteProfileSuccess action on successful deletion", async () => {
    axios.delete.mockResolvedValueOnce({ data: { message: "Profile deleted successfully" } });

    await deleteMyProfile()(store.dispatch);

    expect(dispatch).toHaveBeenCalledWith({
      type: "deleteProfileSuccess",
      payload: "Profile deleted successfully"
    });
  });

  test("should dispatch deleteProfileFailure action on failure", async () => {
    axios.delete.mockRejectedValueOnce({
      response: { data: { message: "Failed to delete profile" } }
    });

    await deleteMyProfile()(store.dispatch);

    expect(dispatch).toHaveBeenCalledWith({
      type: "deleteProfileFailure",
      payload: "Failed to delete profile"
    });
  });
});
