// Test generated by RoostGPT for test SocialMediaTest using AI Type Open AI and AI Model gpt-4

const axios = require("axios");
const { deleteMyProfile } = require("./User");
jest.mock('axios');

describe('deleteMyProfile', () => {
  it('dispatches deleteProfileRequest action when called', async () => {
    const dispatch = jest.fn();
    await deleteMyProfile()(dispatch);
    expect(dispatch).toHaveBeenCalledWith({
      type: "deleteProfileRequest"
    });
  });

  it('dispatches deleteProfileSuccess action if API request is successful', async () => {
    const dispatch = jest.fn();
    const response = { data: { message: 'Profile deleted successfully' } };
    axios.delete.mockResolvedValue(response);
    await deleteMyProfile()(dispatch);
    expect(dispatch).toHaveBeenCalledWith({
      type: "deleteProfileSuccess",
      payload: response.data.message
    });
  });

  it('dispatches deleteProfileFailure action if API request fails', async () => {
    const dispatch = jest.fn();
    const error = { response: { data: { message: 'Failed to delete profile' } } };
    axios.delete.mockRejectedValue(error);
    await deleteMyProfile()(dispatch);
    expect(dispatch).toHaveBeenCalledWith({
      type: "deleteProfileFailure",
      payload: error.response.data.message
    });
  });
});
