// Test generated by RoostGPT for test SocialMediaTest using AI Type Open AI and AI Model gpt-4

const axios = require('axios');
const { forgotPassword } = require('./User.js');

jest.mock('axios');

describe('forgotPassword', () => {
  let dispatch;

  beforeEach(() => {
    dispatch = jest.fn();
  });

  test('dispatches "forgotPasswordRequest" action when called', async () => {
    axios.post.mockResolvedValue({});
    await forgotPassword('test@example.com')(dispatch);
    expect(dispatch).toHaveBeenCalledWith({
      type: 'forgotPasswordRequest'
    });
  });

  test('dispatches "forgotPasswordSuccess" action when request succeeds', async () => {
    axios.post.mockResolvedValue({
      data: {
        message: 'Password reset email sent'
      }
    });
    await forgotPassword('test@example.com')(dispatch);
    expect(dispatch).toHaveBeenCalledWith({
      type: 'forgotPasswordSuccess',
      payload: 'Password reset email sent'
    });
  });

  test('dispatches "forgotPasswordFailure" action when request fails', async () => {
    axios.post.mockRejectedValue({
      response: {
        data: {
          message: 'Email not found'
        }
      }
    });
    await forgotPassword('test@example.com')(dispatch);
    expect(dispatch).toHaveBeenCalledWith({
      type: 'forgotPasswordFailure',
      payload: 'Email not found'
    });
  });
});
