// Test generated by RoostGPT for test ExpressJs using AI Type Open AI and AI Model gpt-4

const axios = require("axios");
const { logoutUser } = require("./User");

jest.mock('axios');

describe('logoutUser', () => {
  beforeEach(() => {
    axios.get.mockClear();
  });

  it('dispatches LogoutUserRequest and LogoutUserSuccess on successful logout', async () => {
    axios.get.mockResolvedValue({});

    const dispatch = jest.fn();
    await logoutUser()(dispatch);

    expect(dispatch).toHaveBeenNthCalledWith(1, { type: 'LogoutUserRequest' });
    expect(axios.get).toHaveBeenCalledWith('/api/v1/logout');
    expect(dispatch).toHaveBeenNthCalledWith(2, { type: 'LogoutUserSuccess' });
  });

  it('dispatches LogoutUserRequest and LogoutUserFailure on failed logout', async () => {
    const error = new Error('Failed to logout');
    error.response = {
      data: {
        message: 'Failed to logout',
      },
    };
    axios.get.mockRejectedValue(error);

    const dispatch = jest.fn();
    await logoutUser()(dispatch);

    expect(dispatch).toHaveBeenNthCalledWith(1, { type: 'LogoutUserRequest' });
    expect(axios.get).toHaveBeenCalledWith('/api/v1/logout');
    expect(dispatch).toHaveBeenNthCalledWith(2, {
      type: 'LogoutUserFailure',
      payload: 'Failed to logout',
    });
  });
});
