// Test generated by RoostGPT for test SocialMediaTest using AI Type Open AI and AI Model gpt-4

const axios = require('axios');
const { followAndUnfollowUser } = require('./User');

jest.mock('axios');

describe('followAndUnfollowUser', () => {
  let id;
  let dispatch;

  beforeEach(() => {
    id = '123';
    dispatch = jest.fn();
  });

  it('dispatches followUserRequest action when called', async () => {
    axios.get.mockResolvedValue({});

    await followAndUnfollowUser(id)(dispatch);

    expect(dispatch).toHaveBeenCalledWith({
      type: 'followUserRequest'
    });
  });

  it('dispatches followUserSuccess action on successful follow', async () => {
    const data = { message: 'Followed successfully' };
    axios.get.mockResolvedValue({ data });

    await followAndUnfollowUser(id)(dispatch);

    expect(dispatch).toHaveBeenCalledWith({
      type: 'followUserSuccess',
      payload: data.message
    });
  });

  it('dispatches followUserFailure action on an error', async () => {
    const error = { response: { data: { message: 'Error message' } } };
    axios.get.mockRejectedValue(error);

    await followAndUnfollowUser(id)(dispatch);

    expect(dispatch).toHaveBeenCalledWith({
      type: 'followUserFailure',
      payload: error.response.data.message
    });
  });
});
