// Test generated by RoostGPT for test SocialMediaTest using AI Type Open AI and AI Model gpt-4

const axios = require('axios');
const { addCommentOnPost } = require('./Post');

jest.mock('axios');

describe('addCommentOnPost', () => {
  let id, comment, dispatch;

  beforeEach(() => {
    id = '123';
    comment = 'This is a comment';
    dispatch = jest.fn();
  });

  afterEach(() => {
    jest.clearAllMocks();
  });

  it('dispatches addCommentRequest and addCommentSuccess upon successful axios request', async () => {
    axios.put.mockResolvedValue({
      data: {
        message: 'Comment added successfully'
      }
    });

    await addCommentOnPost(id, comment)(dispatch);

    expect(dispatch).toHaveBeenCalledWith({ type: 'addCommentRequest' });
    expect(dispatch).toHaveBeenCalledWith({
      type: 'addCommentSuccess',
      payload: 'Comment added successfully'
    });
  });

  it('dispatches addCommentRequest and addCommentFailure upon failed axios request', async () => {
    axios.put.mockRejectedValue({
      response: {
        data: {
          message: 'Failed to add comment'
        }
      }
    });

    await addCommentOnPost(id, comment)(dispatch);

    expect(dispatch).toHaveBeenCalledWith({ type: 'addCommentRequest' });
    expect(dispatch).toHaveBeenCalledWith({
      type: 'addCommentFailure',
      payload: 'Failed to add comment'
    });
  });
});
