// Test generated by RoostGPT for test TestA using AI Type Open AI and AI Model gpt-4

const axios = require("axios");
const { likePost } = require("./Post");
const { applyMiddleware } = require("redux");
const thunk = require("redux-thunk");

jest.mock("axios");

describe("likePost", () => {
  let fakeDispatch;

  beforeEach(() => {
    fakeDispatch = jest.fn();
  });

  it("should dispatch likeRequest action", async () => {
    axios.get.mockResolvedValue({});

    await likePost("1")(fakeDispatch);

    expect(fakeDispatch).toHaveBeenCalledWith({
      type: "likeRequest"
    });
  });

  it("should dispatch likeSuccess action when request is successful", async () => {
    const message = "Post liked successfully";
    axios.get.mockResolvedValue({
      data: {
        message
      }
    });

    await likePost("1")(fakeDispatch);

    expect(fakeDispatch).toHaveBeenCalledWith({
      type: "likeSuccess",
      payload: message
    });
  });

  it("should dispatch likeFailure action when request fails", async () => {
    const message = "Failed to like post";
    axios.get.mockRejectedValue({
      response: {
        data: {
          message
        }
      }
    });

    await likePost("1")(fakeDispatch);

    expect(fakeDispatch).toHaveBeenCalledWith({
      type: "likeFailure",
      payload: message
    });
  });
});
