// Test generated by RoostGPT for test SocialMediaTest using AI Type Open AI and AI Model gpt-4

const axios = require("axios");
const { likePost } = require("./Post");
const { createStore, applyMiddleware } = require("redux");
const thunk = require("redux-thunk");
const { Provider } = require("react-redux");

jest.mock("axios");

describe("likePost", () => {
  let store;
  let mockDispatch;

  beforeEach(() => {
    store = createStore(() => ({}), applyMiddleware(thunk));
    mockDispatch = jest.fn();
  });

  afterEach(() => {
    jest.clearAllMocks();
  });

  test("Should dispatch likeRequest and likeSuccess when API call is successful", async () => {
    const mockData = { message: "Post liked successfully" };
    axios.get.mockResolvedValue({ data: mockData });

    await likePost(1)(mockDispatch);

    expect(mockDispatch).toHaveBeenCalledWith({ type: "likeRequest" });
    expect(axios.get).toHaveBeenCalledWith("/api/v1/post/1");
    expect(mockDispatch).toHaveBeenCalledWith({
      type: "likeSuccess",
      payload: mockData.message
    });
  });

  test("Should dispatch likeRequest and likeFailure when API call fails", async () => {
    const mockError = { response: { data: { message: "Error" } } };
    axios.get.mockRejectedValue(mockError);

    await likePost(1)(mockDispatch);

    expect(mockDispatch).toHaveBeenCalledWith({ type: "likeRequest" });
    expect(axios.get).toHaveBeenCalledWith("/api/v1/post/1");
    expect(mockDispatch).toHaveBeenCalledWith({
      type: "likeFailure",
      payload: mockError.response.data.message
    });
  });
});
