// Test generated by RoostGPT for test TestA using AI Type Open AI and AI Model gpt-4

import React from 'react';
import { render, screen } from '@testing-library/react';
import { Provider } from 'react-redux';
import { Router } from 'react-router-dom';
import { createMemoryHistory } from 'history';
import { createStore } from 'redux';
import App from './App';
import rootReducer from './reducers';

const renderWithRouter = (
  ui,
  {
    route = '/',
    history = createMemoryHistory({ initialEntries: [route] }),
  } = {}
) => {
  return {
    ...render(<Provider store={createStore(rootReducer)}><Router history={history}>{ui}</Router></Provider>),
    history,
  }
}

describe('App Component', () => {
  test('renders login component when user not authenticated', () => {
    const { getByText } = renderWithRouter(<App />, { route: '/account' });
    expect(getByText('Login')).toBeInTheDocument();
  });

  test('renders not found component for non existent route', () => {
    const { getByText } = renderWithRouter(<App />, { route: '/non-existent-route' });
    expect(getByText('Not Found')).toBeInTheDocument();
  });
});
